### ISSUE TITLE
CI 세팅

### ISSUE THREAD

**Issue by sophie-cluml** [jadenow/Rust-exercise#53]
```yml
name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        components: clippy, rustfmt
    - name: Check formatting
      run: cargo fmt -- --check --config group_imports=StdExternalCrate
    - name: Clippy
      run: cargo clippy -- -D warnings -W clippy::pedantic
    - name: Check
      run: cargo check --examples
    - name: markdownlint
      uses: articulate/actions-markdownlint@v1

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest]
    steps:
    - uses: actions/checkout@v4
    - name: Install Rust
      uses: dtolnay/rust-toolchain@stable
    - name: Build
      run: cargo build --examples --verbose
    - name: Run tests
      run: cargo test --verbose
```

위는 ci.yml 파일 예시입니다. 이를 참고하여 github actions 기반 CI를 세팅하면 됩니다.
